Scene 5 floors with angles
course-vortex/concentration pull request #2
Opened 2023-01-30 21:15 UTC by vavadym

found a bug with scene creations

2023-01-30 21:20 UTC, vavadym commented on concentration/ViewControllers/MenuViewController.swift
> +    let scene: SKScene.Type
this is not right place to change it, we will create new task and branch for his bug

2023-01-30 21:20 UTC, vavadym commented on concentration/Scene/FloorsScene.swift
> +    }
need more animations

2023-01-30 21:24 UTC, miroshniktyt requested changes

2023-01-30 21:24 UTC, miroshniktyt commented on concentration/Scene/FloorsScene.swift
> +    func setElements() {
need to separate into another class that will do the calculation of frames for different matrixes

2023-02-03 12:00 UTC, miroshniktyt approved these changes

2023-02-03 12:00 UTC, closed without merging

2023-02-03 12:01 UTC, miroshniktyt commented
good job me