Scene 6
course-vortex/concentration pull request #4
Opened 2023-01-31 08:59 UTC by vladiAN

Added scene with triangle

2023-01-31 09:17 UTC, miroshniktyt commented
one combed please:)

2023-01-31 14:15 UTC, vladiAN commented
done

2023-02-02 18:17 UTC, miroshniktyt requested changes

2023-02-02 18:17 UTC, miroshniktyt commented on concentration/Scene/TriangleScene.swift
> +        let spriteTriangle = SKSpriteNode(texture: triangleTexture, size: .init(width: self.frame.width - (sizeBall * 2), height: 100))
Make a bit smaller so there is a bit more space then just ball size (maybe putting 4 points spacing on each side)

2023-02-02 18:17 UTC, miroshniktyt commented on concentration/Scene/TriangleScene.swift
> +    let sizeBall: CGFloat = 30
Make it bigger, at least 44point, also make it depend in balls number (if there are 100 balls let size be 44, but is there are only 8 balls, make them bigger

2023-02-02 18:17 UTC, miroshniktyt commented on concentration/Scene/TriangleScene.swift
> +        let borderBody =  SKPhysicsBody (edgeLoopFrom: self.frame)
but margins on the button so balls don't go under safe areas, also don't forget that it is different on iPhone se

2023-02-04 11:34 UTC, vladiAN commented on concentration/Scene/TriangleScene.swift
> +    let sizeBall: CGFloat = 30
done

2023-02-04 11:34 UTC, vladiAN commented on concentration/Scene/TriangleScene.swift
> +        let borderBody =  SKPhysicsBody (edgeLoopFrom: self.frame)
done

2023-02-04 21:33 UTC, miroshniktyt approved these changes

2023-02-04 21:33 UTC, merged

2023-02-04 21:41 UTC, vladiAN commented on concentration/Scene/TriangleScene.swift
> +        let borderBody =  SKPhysicsBody (edgeLoopFrom: self.frame)
🫣sorry, but I just now saw the third comment, and made edits only on the first two.